_target_: pytorch_lightning.Trainer

gpus: [1]

min_epochs: 1
max_epochs: 300

precision : 16
enable_progress_bar : True
progress_bar_refresh_rate : 1
weights_summary : 'full'

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
